export * from './HomePage'
export * from './ProfilePage'
export * from './CollectionsPage'
export * from './CollectionPage'
export * from './TasksPage'
export * from  './ValidationPage'
export * from './NewPasswordPage'
export * from './RegisterPage'